#!/usr/bin/env bash
# Displays "Best School" 10 times with hi on 9th using a while loop.


count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
